// Package go_prime is an autogenerated binder stub for package prime.
//   gobind -lang=go github.com/hkurokawa/godroid-sample
//
// File is generated by gobind. Do not edit.
package go_prime

import (
	"github.com/hkurokawa/godroid-sample"
	"golang.org/x/mobile/bind/seq"
)

func proxy_MaxPrime(out, in *seq.Buffer) {
	param_n := in.ReadInt()
	res := prime.MaxPrime(param_n)
	out.WriteInt(res)
}

func init() {
	seq.Register("prime", 1, proxy_MaxPrime)
}
